"""add suppliers table

Revision ID: b44f84473f8c
Revises: 5013fd440fec
Create Date: 2026-07-29 20:37:58.604174

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b44f84473f8c"
down_revision: str | Sequence[str] | None = "5013fd440fec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("contact", sa.String(length=15), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_city"), "suppliers", ["city"], unique=False)
    op.create_index(op.f("ix_suppliers_name"), "suppliers", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suppliers_name"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_city"), table_name="suppliers")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
